lib/crawler_jus_web/router.ex
defmodule CrawlerJusWeb.Router do
  use CrawlerJusWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :check_cache do
    plug(CrawlerJusWeb.Plugs.CheckCache)
  end

  scope "/", CrawlerJusWeb do
    pipe_through :browser

    get "/", SearchController, :index
  end

  scope "/", CrawlerJusWeb do
    pipe_through :browser
    pipe_through :api
    pipe_through :check_cache

    get("/search-process", SearchController, :show)
  end

  # Other scopes may use custom stacks.
  # scope "/api", CrawlerJusWeb do
  #   pipe_through :api
  # end
end

lib/crawler_jus_web/controllers/search_controller.ex
defmodule CrawlerJusWeb.SearchController do
  use CrawlerJusWeb, :controller

  alias CrawlerJus.{CrawlerEngine, RedisCache, Scrapper}
  alias CrawlerJus.Processes

  action_fallback(CrawlerJusWeb.ErrorFallbackController)

  def index(conn, _params) do
    courts = Processes.list_courts()

    render(conn, "index.html", courts: courts, process: nil)
  end

  def show(%{assigns: %{cache_expired: true}} = conn, %{
        "court_id" => court_id,
        "process_code" => process_code
      }) do
    with {:ok, html_body, _headers} <- CrawlerEngine.start_crawler(process_code),
         {:ok, scrapped_data} <- Scrapper.start_scrapper(html_body),
         {:ok, data} <-
           Processes.create_or_update_process_data(process_code, scrapped_data, court_id),
         {:ok, _process_code} <-
           RedisCache.set_process_cache_ttl(process_code, data) do
      conn
      |> put_status(200)
      |> json(%{data: %{process_data: data}})
    end
  end

  def show(%{assigns: %{process_cached_data: process_data}} = conn, _params) do
    conn
    |> put_status(200)
    |> json(%{data: %{process_data: process_data}})
  end
end

lib/crawler_jus_web/views/search_view.ex
defmodule CrawlerJusWeb.SearchView do
  use CrawlerJusWeb, :view
end

lib/crawler_jus_web/templates/search/_search_header.html.eex
<section>
  <h1>Buscar</h1>
  <p> Selecione um tribunal para listar os processos ou buscar pelo número unificado.</p>
</section>
 <%= form_for @conn, Routes.search_path(@conn, :show), [method: :get], fn f -> %>
      <%= select f, :court_id, [{"Tribunal de Alagoas",1}],
        prompt: "Escolha o Tribunal", required: true %>
      </div>
      <%= search_input f, :process_code , prompt: "Numero do processo", required: true%>
      <%= submit "Search" %>
  <% end %>

lib/crawler_jus_web/templates/search/index.html.eex
<div id="search-page">
  <section class="row">
    <%= react_component("Components.ProcessSearchProvider", %{courts: @courts}) %>
  </section>
</div>